sonar.projectKey=cohort-9-mern-9754-zuhaib
sonar.projectName=Notes App
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.scannerwork/**,**/public/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
